name: Basic WASI SDK Usage

on:
  push:
    branches:
      [
        main,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: '25'

      - name: Build WebAssembly module
        run:
          |
          # Create a simple C program
          cat > hello.c << 'EOF'
          #include <stdio.h>

          int main() {
              printf("Hello, WebAssembly world!\n");
              return 0;
          }
          EOF

          # Compile to WebAssembly
          clang hello.c -o hello.wasm

          # Show the compiled file
          ls -la hello.wasm
          file hello.wasm
