name: CMake with WASI SDK

on:
  push:
    branches:
      [
        main,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: '25'

      - name: Configure CMake
        run:
          |
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=$WASI_SDK_PATH/share/cmake/wasi-sdk.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: List build artifacts
        run: find build -name "*.wasm" -ls
