name: Matrix Build with Multiple WASI SDK Versions

on:
  push:
    branches:
      [
        main,
      ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wasi-sdk-version:
          [
            '23',
            '24',
            '25',
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WASI SDK
        uses: konsumer/install-wasi-sdk@v1
        with:
          version: ${{ matrix.wasi-sdk-version }}

      - name: Show installation info
        shell: bash
        run:
          |
          echo "WASI SDK Version: ${{ matrix.wasi-sdk-version }}"
          clang --version
          echo "WASI SDK Path: $WASI_SDK_PATH"

      - name: Build test program
        shell: bash
        run:
          |
          cat > test.c << 'EOF'
          #include <stdio.h>

          int main() {
              printf("Built with WASI SDK v${{ matrix.wasi-sdk-version }}!\n");
              return 0;
          }
          EOF

          clang test.c -o test.wasm
          ls -la test.wasm
